language: ruby

os: osx

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_install:
  - brew update
  - brew --version
  - gem install rubocop rubocop-performance rubocop-rspec
  - gem install activesupport -v 5.2.4.1
  - mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - cd /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade

script:
  - rubocop
  - brew cu -y
